# Config file which contains the probed ROI sizes and other additonal information about the 11 probed CRC LM samples.
'01':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [15, 15]

    spot_position_rotation: false

    image_rotation: 18

#Sample ID Patient 2
'02':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]

    spot_position_rotation: true
  
'03':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [5, 5]

    spot_position_rotation: false

'04':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]

    spot_position_rotation: true

'05':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]

    spot_position_rotation: false

'06':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]

    spot_position_rotation: false

    #required if a 20X H&E image is close to the border of the 10X H&E image 
    template_cropping:
        crop_FOV: 1 # ROI number, index will be one lower
        left: 400

'7a':
    ROI_dimensions:
    - [20, 20]
    - [10, 10]

    spot_position_rotation: false

'7b':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]

    spot_position_rotation: false

'08':
    ROI_dimensions:
    - [10, 20]
    - [10, 10]
    - [18, 9]
    - [5, 5]
    - [5, 10]

    spot_position_rotation: false

'09':
    ROI_dimensions:
    - [8, 8]
    - [5, 5]
    - [7, 7]
    - [7, 7]
    - [6, 6]
    - [4, 4]
    - [4, 4]

    spot_position_rotation: false

'10':
    ROI_dimensions:
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]
    - [10, 10]

    spot_position_rotation: false



